### ISSUE TITLE
Invalid provider type specified

### ISSUE THREAD

**Issue by jeancz** [MewsSystems/eet#15]
I have ran into a very strange issue on Windows 10 (.NET framework 4.6). I received CryptographicException with message "Invalid provider type specified" when tried to load  [private key](https://github.com/MewsSystems/eet/blob/master/src/Mews.Eet/Dto/Certificate.cs#L36).

Finally (after few hours) I have found solution.
 - I have added "X509KeyStorageFlags.MachineKeySet" flag when private key is imported to the [collection](https://github.com/MewsSystems/eet/blob/master/src/Mews.Eet/Dto/Certificate.cs#L28)
- I have added "X509KeyStorageFlags.DefaultKeySet" flag to the [X509Certificate2 contructor](https://github.com/MewsSystems/eet/blob/master/src/Mews.Eet/Dto/Certificate.cs#L14)

Can somebody confirm this issue?

**Comment by jirihelmich** [comment]
Isn't it connected to http://stackoverflow.com/questions/9951729/x509certificate-constructor-exception/10048789#10048789 ?

**Comment by jeancz** [comment]
I don't  think so. Exception has occurred when tried read private key. By the way I use the library in winforms.

**Comment by jirihelmich** [comment]
Never met this issue on Windows 10 and no one got back to me with this. Can you file a PR with your changes?

**Comment by jeancz** [comment]
Nice reading about [this](http://paulstovell.com/blog/x509certificate2). When X509Certificate2 is loaded
,the private key is written to somewhere locally (depends on flags).

**Comment by jirihelmich** [comment]
Thanks, I will learn a bit more about this and if it works for us as well, I will merge your PR.

**Comment by jeancz** [comment]
It looks like there is some problem in domain user profile finally. My solution is only workaround. So can ignore it.
