### ISSUE TITLE
Problem with private key if certificate read from store

### ISSUE THREAD

**Issue by ildra** [MewsSystems/eet#20]
Hello,
When I read certificate from file everything works fine , with simmilar codeas  in your samples.
I have problem where take certificate from Certificate (Local computer- > Presonal ->Certificates , using  Thumbprint, like this 
X509Certificate2Collection certCollectio = certStore.Certificates.Find(X509FindType.FindByThumbprint, "285d7b505215974307fc4ce6852d5dbe7bxxxx", false);
 X509Certificate2 = pepeColection[0];
I got certificate which looks like certificate colection got from file.
After that I got Private key from  certificate. When I send request to Web service I got message:
Error number : 4 , error message: Neplatny podpis SOAP zpravy (Invalid SOAP message signature)
I use playground environment. Is it allowed (read from stored certificate) in playground environment?
Do you have any idea what is wrong?
Thank you in advance for answer.
BR! Dragan

**Comment by ildra** [comment]
Hello,
I check code in made some mistakes. Ignore my first post: This is the corrected code:
When I read certificate from file everything works fine , with simmilar codeas in your samples.
I have problem where take certificate from store: Certificate (Local computer- > Presonal ->Certificates , using Thumbprint, like this
X509Certificate2Collection certCollection = certStore.Certificates.Find(X509FindType.FindByThumbprint, "285d7b505215974307fc4ce6852d5dbe7bxxxx", false);
X509Certificate2 = certCollection[0];
I got certificate which looks like certificate colection got from file.
After that I got Private key from this certificate collection . 

private RSACryptoServiceProvider ComputeKey(X509Certificate2Collection certCollection)
        {
            var certificateCollection = new X509Certificate2Collection();
            certificateCollection = certCollection;
            foreach (var certificate in certificateCollection)
            {
                if (!certificate.HasPrivateKey)
                {
                    continue;
                }
                var key = certificate.PrivateKey as RSACryptoServiceProvider;
                var exportParameters = key.ExportParameters(includePrivateParameters: true);
                var cspParameters = new CspParameters { ProviderName = "Microsoft Enhanced RSA and AES Cryptographic Provider" };
                var result = new RSACryptoServiceProvider(cspParameters);
                result.ImportParameters(exportParameters);
                return result;
            }

            throw new ArgumentException("The provided certificate does not have any private keys.");
        }
When I send request to Web service I got message:
Error number : 4 , error message: Neplatny podpis SOAP zpravy (Invalid SOAP message signature)
I use playground environment. Is it allowed (read from stored certificate) in playground environment?
Do you have any idea what is wrong?
Thank you in advance for answer.
BR! Dragan

**Comment by jirihelmich** [comment]
Hello, please reformat your issue and try to make it as short as possible.

The error no. 4 you get is an error from EET servers. Only playground certificates can be used while communicating with playground. If you use a production certificate, that's the core of your problem - using production certificate with playground.

**Comment by ildra** [comment]
Hello,
I use playground certificate in playground environment, that is OK for shure, because everything woks fine if I read data from file.
If I use certificate from certificate store : Certificates (Local computer- > Presonal ->Certificates , using Thumbprint (FindByThumbprint) method I got  error no. 4  from EET servers. Do you have any sample how to compue Kay in that case?

**Comment by jirihelmich** [comment]
Hello, I do not have any samples of reading certificates from stores. As loading from file is working well, this looks like an issue unrelated to the library. Until you prove otherwise, closing the issue.

**Comment by staybfutrell** [comment]
I had this issue as well.  Once you get the certificate from the store it can be exported into a byte array using the following statement:

var certData = cert.Export(X509ContentType.Pkcs12, "<cert password>");

In this case certData is used as the data parameter in the Certificate constructor.

var certificate = new Certificate(
    password: "<cert password>",
    data: certData
);

However even after exporting the cert using the byte array from the store cert to perform an EET request it still fails with error number 4 - even if using the playground certificate.
