### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by staybfutrell** [MewsSystems/eet#23]
I am in the Eastern Time Zone and when I send a request I get a fiscal code but I also get a warning that the date and time of sale is newer than the date and time of data message acceptance.

It appears when sending the request that the time in the header XML element has similar time (hours:minutes:seconds) as the time in the response but the time zone code is different.

Example: in my request the time in the header was 2017-03-07T22:16:20-05:00.  In the response the time was 2017-03-07T22:16:23+01:00.  Because my machine is set to Eastern time EET is thinking that the request was sent 6 hours ahead of the actual time the request was sent.

**Comment by jirihelmich** [comment]
Hi,

thanks for the feedback. Would you be able to prepare a failing test?

**Comment by staybfutrell** [comment]
Actually the existing unit tests SendRevenueSimple() and SendRevenue() in the Basics.cs class will fail if the time zone on the computer is set to Eastern Time.  I verified this by setting the time zone to UTC and those two unit tests passed.

**Comment by jirihelmich** [comment]
Thanks, identified the bug.

**Comment by jirihelmich** [comment]
As the government made it now clear that it is possible to use any timezone identifier, not only +01:00 or +02:00, the fix of the issue was pretty straightforward. Thank you. Will be releasing this to NuGet in a minute.

**Comment by staybfutrell** [comment]
Works great - thanks for the quick fix!
