### ISSUE TITLE
Using a X509Certificate2 from the cert store instead of a file

### ISSUE THREAD

**Issue by staybfutrell** [MewsSystems/eet#24]
This may not necessarily be considered a bug but so far I have been unable to use a certificate stored in the certificate store instead of a certificate file stored locally.

In my attempt to use a certificate from the store several methods were attempted to export the certificate data into a byte array to pass into the Certificate constructor.

These two methods allowed the request to be sent but resulted in an EET error code 4:
- cert.Export(X509ContentType.Pfx, "cert password");
- cert.Export(X509ContentType.Pkcs12, "cert password");

These three methods result in no private key errors when executing the Certificate's ComputeKey method:
- cert.GetRawCertData();
- cert.Export(X509ContentType.Cert);
- cert.Export(X509ContentType.Cert, "cert password");

Using the CZ00000019 p12 file will send a request and get a response with a fiscal code.  When attempting to use the certificate after retrieving it from the certificate store EET has yet to return a result with a fiscal code.  The store certificate has the appropriate permissions assigned to it to allow it to be accessed and exported.

**Comment by jirihelmich** [comment]
I will try to have a look at this, but as I am currently working on a similar thing for Austria, my time is very limited. It would be great if someone would participate on this and try to find a solution.

**Comment by staybfutrell** [comment]
I'll branch and commit what I have.  While this branch allows a certificate to be passed in through the constructor it still only works if the certificate was created from the cert file versus retrieving it from the store.

**Comment by jirihelmich** [comment]
Could be fixed by #29.

**Comment by jirihelmich** [comment]
Until proven otherwise, closing.
