### ISSUE TITLE
Soap signature error

### ISSUE THREAD

**Issue by mmaganti** [MewsSystems/eet#27]
It works fine using the test certificate against the playground environment and production verification mode. Now clients have provided me the production certificate and I get error 'Neplatny podpis SOAP zpravy' both against playground and productions URLs.   Appreciate any help in resolving the issue.

**Comment by jirihelmich** [comment]
You cannot use production certificate on playground, that does not work as playground and production have different certificate authorities.

Otherwise I am not sure how to help you as the library works for a lot of people already, therefore it does not seem to be an issue of the library. Make sure the certificate is valid and you use it against production only.

**Comment by mmaganti** [comment]
I am using the production certificate against production service. Certificate is valid until 2020 and issued by/to right authority. I have copied below the SOAP request XML if it can provide any details. One thing I notice is that the tag elements are not prefixed with 'eet' namespace. Could that cause any issues?

<Trzba xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://fs.mfcr.cz/eet/schema/v3"><Hlavicka uuid_zpravy="55fb2775-ff6c-4410-a4d3-ed461e5be5a8" dat_odesl="2017-06-01T21:24:45-04:00" prvni_zaslani="false" /><Data dic_popl="CZ00000019" dic_poverujiciho="CZ28999428" id_provoz="11" id_pokl="3" porad_cis="269" dat_trzby="2017-06-01T20:16:12-04:00" celk_trzba="53.84" zakl_nepodl_dph="4.34" zakl_dan1="47.76" dan1="6.08" pouzit_zboz1="0.00" urceno_cerp_zuct="0.00" cerp_zuct="0.00" rezim="0" /><KontrolniKody><pkp digest="SHA256" cipher="RSA2048" encoding="base64">PkujnGTL9aF/OeJj8Kzo+NeMaHT9Dj7eNzHjp+iJB7suz99DTpIR9mEqFEB7sBb0+TH/3K9EjGkw1LFn3yk0ouGg6Sak/3r4EldCXzOrWOU4UlGYg/lfABWDtssEJBN4+5jgArqfg0xYFpUT9fhxebxYhh9MnFMElZQkie/IVUrkl51BnyeX3gIj6uZp5lIL62GZe5Q8G4OrwwbcxtTWzlIuYp7QWUxRkvsjBrx4WR0bWwrneCBfi2xHTjowdVK5ebZ4mIFSYYJgHm3/NZCiyxrxYdlEAztazSUHkgiyDaFH0925t/ELo/nwEc1OoGBFQmgl85xE42SVzE8XosaUFQ==</pkp><bkp digest="SHA1" encoding="base16">6A82505A-C4B6DFE1-2E4B8B32-701FFF03-DBF41C87</bkp></KontrolniKody></Trzba>

**Comment by mmaganti** [comment]
Hi
I am using the production certificate against production service. Certificate is valid until 2020 and issued by/to right authority. I have copied below the SOAP request XML if it can provide any details. One thing I notice is that the tag elements are not prefixed with 'eet' namespace. Could that cause any issues?
<Trzba xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://fs.mfcr.cz/eet/schema/v3"><Hlavicka uuid_zpravy="55fb2775-ff6c-4410-a4d3-ed461e5be5a8" dat_odesl="2017-06-01T21:24:45-04:00" prvni_zaslani="false" /><Data dic_popl="CZ00000019" dic_poverujiciho="CZ28999428" id_provoz="11" id_pokl="3" porad_cis="269" dat_trzby="2017-06-01T20:16:12-04:00" celk_trzba="53.84" zakl_nepodl_dph="4.34" zakl_dan1="47.76" dan1="6.08" pouzit_zboz1="0.00" urceno_cerp_zuct="0.00" cerp_zuct="0.00" rezim="0" /><KontrolniKody><pkp digest="SHA256" cipher="RSA2048" encoding="base64">PkujnGTL9aF/OeJj8Kzo+NeMaHT9Dj7eNzHjp+iJB7suz99DTpIR9mEqFEB7sBb0+TH/3K9EjGkw1LFn3yk0ouGg6Sak/3r4EldCXzOrWOU4UlGYg/lfABWDtssEJBN4+5jgArqfg0xYFpUT9fhxebxYhh9MnFMElZQkie/IVUrkl51BnyeX3gIj6uZp5lIL62GZe5Q8G4OrwwbcxtTWzlIuYp7QWUxRkvsjBrx4WR0bWwrneCBfi2xHTjowdVK5ebZ4mIFSYYJgHm3/NZCiyxrxYdlEAztazSUHkgiyDaFH0925t/ELo/nwEc1OoGBFQmgl85xE42SVzE8XosaUFQ==</pkp><bkp digest="SHA1" encoding="base16">6A82505A-C4B6DFE1-2E4B8B32-701FFF03-DBF41C87</bkp></KontrolniKody></Trzba>

ThanksMurty
 

    On Friday, June 2, 2017 1:10 AM, Jiří Helmich <notifications@github.com> wrote:
 

 You cannot use production certificate on playground, that does not work as playground and production have different certificate authorities.Otherwise I am not sure how to help you as the library works for a lot of people already, therefore it does not seem to be an issue of the library. Make sure the certificate is valid and you use it against production only.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by jirihelmich** [comment]
You send "CZ00000019" asi VAT number (DIČ) and use the special tax mode (daňové pověření). I do not believe that is correct -> the VAT number does not match the VAT number of the certificate owner -> the SOAP signature is not valid.

**Comment by mmaganti** [comment]
I ended up copying wrong XML in the previous comment. My apologies. This is correct request XML that was sent which doesn't work (which gets invalid SOAP signature error). I get the error both in verification and operation modes.
<Trzba xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://fs.mfcr.cz/eet/schema/v3"> <Hlavicka uuid_zpravy="eb78c2f0-2b01-4557-87c1-c01f930a0ddc" dat_odesl="2017-06-02T10:08:29-04:00" prvni_zaslani="true" overeni="true" /> <Data dic_popl="CZ28999428" id_provoz="11" id_pokl="3" porad_cis="287" dat_trzby="2017-06-02T10:08:07-04:00" celk_trzba="109.38" zakl_nepodl_dph="0.00" zakl_dan1="96.49" dan1="12.89" pouzit_zboz1="0.00" urceno_cerp_zuct="0.00" cerp_zuct="0.00" rezim="0" /> <KontrolniKody> <pkp digest="SHA256" cipher="RSA2048" encoding="base64">O0BBA0/YIyN6ko3UWHlCD8gjkAlsFIijoCERCiMTNyQIscf1ICZrJybT3YSBPR35DSKsHsLiklCMxXR/NLB6AzRhABXNjgU6u4jNLLj4TS4hXwVrqUYDa7/u1tYpBOCC23S4Ux5jprz7xPeWEDfJgam/Hu72C/OSCrsh7DK/k6WYcZeDbuWDtOCq+EpFR8lCsSExUZ7BuCwweRmcRROXLMCQh+jv04hlVKPurfTwUdxiphudKxkqm1R7vX/y3HIaJg+B4eg5sdBYw9M9Gjf7ipgnE/NTp4U2KqYbHCMT00ijxzYmn6S+MvLtw9UeO8ExCa6+vwPQmZ9gGYIU4baBsg==</pkp> <bkp digest="SHA1" encoding="base16">B1B693B0-6D93A523-5AF7ADE8-A43A43EA-2AC210E2</bkp> </KontrolniKody></Trzba> 

    On Friday, June 2, 2017 10:02 AM, Jiří Helmich <notifications@github.com> wrote:
 

 Closed #27.—
